export type Language =
  | 'pt-BR'
  | 'en'
  | 'es'
  | 'zh'
  | 'hi'
  | 'ar'
  | 'bn'
  | 'ru'
  | 'ja'
  | 'de'
  | 'fr'
  | 'it'
  | 'ko'
  | 'tr'
  | 'pl'
  | 'nl'
  | 'sv'
  | 'uk'
  | 'vi'
  | 'th';

const LANGUAGE_LIST: Language[] = [
  'pt-BR',
  'en',
  'es',
  'zh',
  'hi',
  'ar',
  'bn',
  'ru',
  'ja',
  'de',
  'fr',
  'it',
  'ko',
  'tr',
  'pl',
  'nl',
  'sv',
  'uk',
  'vi',
  'th',
];

const isLanguage = (v: unknown): v is Language =>
  typeof v === 'string' && (LANGUAGE_LIST as string[]).includes(v);

const detectLanguageFromURL = (): Language => {
  if (typeof window === 'undefined') return 'en';
  
  const hostname = window.location.hostname;
  const subdomain = hostname.split('.')[0];
  
  const languageMap: Record<string, Language> = {
    'pt': 'pt-BR',
    'en': 'en',
    'es': 'es',
    'zh': 'zh',
    'hi': 'hi',
    'ar': 'ar',
    'bn': 'bn',
    'ru': 'ru',
    'ja': 'ja',
    'de': 'de',
    'fr': 'fr',
    'it': 'it',
    'ko': 'ko',
    'tr': 'tr',
    'pl': 'pl',
    'nl': 'nl',
    'sv': 'sv',
    'uk': 'uk',
    'vi': 'vi',
    'th': 'th',
  };
  
  return languageMap[subdomain] || 'en';
};

const detectedLanguage = detectLanguageFromURL();

export const LANGUAGE_CONFIG = {
  defaultLanguage: detectedLanguage,
  currentLanguage: detectedLanguage,
  availableLanguages: {
    'pt-BR': { name: 'Português', flag: '🇧🇷', code: 'pt-BR' },
    en: { name: 'English', flag: '🇺🇸', code: 'en' },
    es: { name: 'Español', flag: '🇪🇸', code: 'es' },
    zh: { name: '中文', flag: '🇨🇳', code: 'zh' },
    hi: { name: 'हिन्दी', flag: '🇮🇳', code: 'hi' },
    ar: { name: 'العربية', flag: '🇸🇦', code: 'ar' },
    bn: { name: 'বাংলা', flag: '🇧🇩', code: 'bn' },
    ru: { name: 'Русский', flag: '🇷🇺', code: 'ru' },
    ja: { name: '日本語', flag: '🇯🇵', code: 'ja' },
    de: { name: 'Deutsch', flag: '🇩🇪', code: 'de' },
    fr: { name: 'Français', flag: '🇫🇷', code: 'fr' },
    it: { name: 'Italiano', flag: '🇮🇹', code: 'it' },
    ko: { name: '한국어', flag: '🇰🇷', code: 'ko' },
    tr: { name: 'Türkçe', flag: '🇹🇷', code: 'tr' },
    pl: { name: 'Polski', flag: '🇵🇱', code: 'pl' },
    nl: { name: 'Nederlands', flag: '🇳🇱', code: 'nl' },
    sv: { name: 'Svenska', flag: '🇸🇪', code: 'sv' },
    uk: { name: 'Українська', flag: '🇺🇦', code: 'uk' },
    vi: { name: 'Tiếng Việt', flag: '🇻🇳', code: 'vi' },
    th: { name: 'ไทย', flag: '🇹🇭', code: 'th' },
  },
};

export const setLanguage = (lang: Language) => {
  LANGUAGE_CONFIG.currentLanguage = lang;
};

export const getCurrentLanguage = () => {
  return LANGUAGE_CONFIG.currentLanguage;
};

export const getTranslations = () => {
  return TRANSLATIONS[getCurrentLanguage()] || TRANSLATIONS.en;
};

const EN_TRANSLATIONS = {
  siteTitle: 'Free Online Tools',
  siteName: 'Online Tools',
  siteDescription: 'Access a comprehensive suite of free online tools for PDF editing, video conversion, image processing and QR code generation. Convert, compress and optimize files securely in your browser.',

  home: 'Home',
  tools: 'Tools',
  about: 'About',
  contact: 'Contact',
  legal: 'Legal',
  privacyPolicy: 'Privacy Policy',
  termsOfUse: 'Terms of Use',
  sitemap: 'Sitemap',
  languages: 'Languages',
  skipToContent: 'Skip to content',
  toggleTheme: 'Toggle theme',
  closeMenu: 'Close menu',
  openMenu: 'Open menu',
  search: 'Search',

  toolsPageTitle: 'Tools',
  toolsPageDescription: 'Explore our collection of free online tools.',
  toolsPageKeywords: ['online tools', 'utilities', 'free tools'],
  aboutPageTitle: 'About',
  aboutPageDescription: 'Learn more about Online Tools.',
  aboutPageKeywords: ['about', 'online tools', 'information'],

  heroTitle: 'Free Online Tools',
  heroSubtitle: 'Everything you need in one place',
  heroDescription: 'Access a complete collection of free online tools to facilitate your work and increase your productivity.',

  searchPlaceholder: 'Search tools...',
  allCategories: 'All',
  totalTools: 'Total:',
  toolsCounter: 'tools available',

  footerText: 'All rights reserved.',
  privacyText: 'We use cookies to improve your experience.',
  cookieMessage: 'This site uses cookies to ensure you get the best experience.',
  acceptCookies: 'Accept',
  madeWith: 'Made with',
  by: 'by',
  followUs: 'Follow Us',
  navigation: 'Navigation',

  notebookTitle: 'Notepad',
  notebookDescription: 'Write and save your notes quickly.',

  // Legal page translations
  legalCompanyInfo: 'Company Information',
  legalCompanyInfoText: 'Muiltools is a web-based platform providing various online tools and utilities for productivity and convenience.',
  legalIntellectualProperty: 'Intellectual Property',
  legalIntellectualPropertyText: 'All content, features, and functionality on this website are owned by Muiltools and are protected by international copyright, trademark, and other intellectual property laws.',
  legalLiability: 'Limitation of Liability',
  legalLiabilityText: 'Muiltools provides tools and services "as is" without any warranties. We are not liable for any damages arising from the use of our services.',
  legalGoverningLaw: 'Governing Law',
  legalGoverningLawText: 'These legal terms are governed by and construed in accordance with applicable laws.',
  legalContact: 'Contact Information',
  legalContactText: 'If you have any questions about these legal terms, please contact us through our contact page.',

  // Privacy Policy translations
  privacyIntro: 'Introduction',
  privacyIntroText: 'This Privacy Policy describes how Muiltools collects, uses, and protects your information when you use our website and services.',
  privacyDataCollection: 'Data Collection',
  privacyDataCollectionText: 'We collect information you provide directly to us, such as when you use our tools, contact us, or interact with our website.',
  privacyCookies: 'Cookies and Tracking',
  privacyCookiesText: 'We use cookies and similar technologies to improve your experience, analyze usage, and provide personalized content.',
  privacyDataUse: 'How We Use Your Data',
  privacyDataUseText: 'We use collected information to provide, maintain, and improve our services, communicate with you, and ensure security.',
  privacyDataSharing: 'Data Sharing',
  privacyDataSharingText: 'We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy.',
  privacyRights: 'Your Rights',
  privacyRightsText: 'You have the right to access, update, or delete your personal information. Contact us if you wish to exercise these rights.',
  privacyContact: 'Contact Us',
  privacyContactText: 'If you have any questions about this Privacy Policy, please contact us through our contact page.',

  // Terms of Use translations
  termsAcceptance: 'Acceptance of Terms',
  termsAcceptanceText: 'By accessing and using Muiltools, you accept and agree to be bound by the terms and provision of this agreement.',
  termsUseOfService: 'Use of Service',
  termsUseOfServiceText: 'You may use our service for lawful purposes only. You agree not to use the service in any way that violates any applicable laws or regulations.',
  termsUserContent: 'User Content',
  termsUserContentText: 'You retain ownership of any content you submit, post or display on or through the service. You are responsible for the content you provide.',
  termsProhibitedUse: 'Prohibited Uses',
  termsProhibitedUseText: 'You may not use our service for any illegal or unauthorized purpose, to violate any laws, or to harm or exploit others.',
  termsDisclaimer: 'Disclaimer',
  termsDisclaimerText: 'The information on this website is provided on an "as is" basis. We disclaim all warranties and make no representations regarding the accuracy or reliability of the content.',
  termsModification: 'Modification of Terms',
  termsModificationText: 'We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting on the website.',
  termsContact: 'Contact Information',
  termsContactText: 'If you have any questions about these Terms of Use, please contact us through our contact page.',
  notebook: {
    confirmClear: 'Are you sure you want to clear the notes?',
    saved: 'Saved',
    save: 'Save',
    download: 'Download',
    clear: 'Clear',
    placeholder: 'Type your notes here...',
    characterCount: 'characters',
    yourNotes: 'Your Notes',
    lastModified: 'Last modified',
    autoSaveTitle: 'Auto Save',
    autoSaveDescription: 'Your notes are automatically saved every few seconds.',
    privacyTitle: 'Privacy',
    privacyDescription: 'All content is stored only in your browser.',
    exportTitle: 'Export',
    exportDescription: 'Download your notes as a text file.',
  },

  ocrTitle: 'OCR - Text Recognition',
  ocrDescription: 'Extract text from images using optical character recognition.',
  ocr: {
    uploadImage: 'Upload Image',
    extractText: 'Extract Text',
    extractedText: 'Extracted Text',
    copyText: 'Copy Text',
    downloadText: 'Download Text',
    processing: 'Processing...',
    noTextFound: 'No text found in the image.',
    error: 'Error processing image.',
    supportedFormats: 'Supported formats: JPG, PNG, GIF, BMP, WEBP',
    dragDrop: 'Drag and drop an image here or click to select',
  },

  passwordGeneratorTitle: 'Password Generator',
  passwordGeneratorDescription: 'Generate secure passwords with customizable options.',
  passwordGenerator: {
    generate: 'Generate Password',
    copy: 'Copy',
    length: 'Length',
    includeUppercase: 'Include Uppercase',
    includeLowercase: 'Include Lowercase',
    includeNumbers: 'Include Numbers',
    includeSymbols: 'Include Symbols',
    excludeSimilar: 'Exclude Similar Characters',
    generatedPassword: 'Generated Password',
    copied: 'Copied!',
    strength: 'Strength',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    veryStrong: 'Very Strong',
  },

  characterCounterTitle: 'Character Counter',
  characterCounterDescription: 'Count characters, words, and lines in your text.',
  characterCounter: {
    placeholder: 'Type or paste your text here...',
    characters: 'Characters',
    charactersNoSpaces: 'Characters (no spaces)',
    words: 'Words',
    lines: 'Lines',
    paragraphs: 'Paragraphs',
    readingTime: 'Reading time',
    minutes: 'minutes',
    clear: 'Clear',
  },

  qrGeneratorTitle: 'QR Code Generator',
  qrGeneratorDescription: 'Generate QR codes for text, URLs, and more.',
  qrGenerator: {
    inputPlaceholder: 'Enter text or URL',
    generate: 'Generate QR Code',
    download: 'Download QR Code',
    size: 'Size',
    errorCorrection: 'Error Correction',
    low: 'Low',
    medium: 'Medium',
    quartile: 'Quartile',
    high: 'High',
    enterContent: 'Please enter content to generate QR code',
    errorGenerating: 'Error generating QR code',
    settings: 'Settings',
    contentType: 'Content Type',
    content: 'Content',
    color: 'Color',
    preview: 'Preview',
    generated: 'Generated QR Code',
    previewText: 'QR Code will appear here',
    contentTypes: {
      text: 'Text',
      url: 'URL',
      wifi: 'Wi-Fi',
      vcard: 'Business Card',
      sms: 'SMS',
    },
    placeholders: {
      text: 'Enter your text here...',
      url: 'https://example.com',
      wifi: 'WIFI:T:WPA;S:NetworkName;P:password;;',
      vcard: 'BEGIN:VCARD\nVERSION:3.0\nFN:Full Name\nORG:Company\nTEL:+1234567890\nEMAIL:email@example.com\nEND:VCARD',
      sms: 'SMSTO:+1234567890:Your message here',
    },
  },

  pdfValidatorTitle: 'PDF/A Validator',
  pdfValidatorDescription: 'Validate PDF files for PDF/A compliance.',
  pdfValidator: {
    uploadFile: 'Upload PDF File',
    validate: 'Validate',
    validating: 'Validating...',
    valid: 'Valid PDF/A',
    invalid: 'Invalid PDF/A',
    errors: 'Errors found',
    dragDrop: 'Drag and drop a PDF file here or click to select',
    supportedFormat: 'Supported format: PDF',
  },

  pdfaValidatorTitle: 'PDF/A Validator',
  pdfaValidatorDescription: 'Validate PDF files for PDF/A compliance and standards.',
  pdfaValidator: {
        selectFile: 'Select file',
        selectFileTitle: 'Select File',
        selectButton: 'Select File',
        dragDrop: 'Drag and drop your PDF file here',
        dragDropHint: 'Drag and drop your PDF file here',
        onlyPdfSupported: 'Only PDF files are supported',
        onlyPdfHint: 'Only PDF files are supported',
        pdfOnlyAlert: 'Only PDF files are supported',
    validating: 'Validating...',
     checkingCompliance: 'Checking PDF/A compliance',
     checkingPdfa: 'Checking PDF/A compliance',
     results: 'Results',
     resultTitle: 'Results',
     clear: 'Clear',
     file: 'File:',
     fileLabel: 'File:',
     size: 'Size:',
     sizeLabel: 'Size:',
    validatedAt: 'Validated at',
    valid: 'Valid',
    invalid: 'Invalid',
    detectedLevel: 'Detected level',
    issues: 'Issues',
    warnings: 'Warnings',
    aboutTitle: 'About',
    aboutItems: [
      'PDF/A is an archival format for long-term preservation',
      'Ensures documents remain accessible over time',
      'Removes dependencies on external resources',
      'Standardizes fonts and color spaces'
    ],
    tipsTitle: 'Tips',
    tipsItems: [
      'Use embedded fonts for better compatibility',
      'Avoid transparency and complex graphics',
      'Include proper metadata and document structure',
      'Test with multiple validators for accuracy'
    ],
    documentTitleUndefined: 'Document title not defined',
    documentCreatorUndefined: 'Document creator not defined',
    documentProducerUndefined: 'Document producer not defined',
    pdfaMetadataNotFound: 'PDF/A metadata not found in document',
    noComplianceIdentifiers: 'Document does not contain PDF/A compliance identifiers',
    keywordsRecommendedPdfa1b: 'Keywords recommended for PDF/A-1B',
    subjectRecommendedPdfa2b3b: 'Subject recommended for PDF/A-2B or PDF/A-3B',
    documentNoPages: 'PDF document contains no pages',
        noPagesFound: 'PDF document contains no pages',
        errorProcessingPdf: 'Error processing PDF file',
        processingError: 'Error processing PDF file',
        fileCorruptedOrInvalid: 'File may be corrupted or not a valid PDF',
        corruptedFileError: 'File may be corrupted or not a valid PDF'
  },

  dependenciesTitle: 'Dependencies Status',
  dependenciesDescription: 'Check the status of project dependencies.',
  dependencies: {
    checking: 'Checking dependencies...',
    upToDate: 'Up to date',
    outdated: 'Outdated',
    vulnerable: 'Vulnerable',
    unknown: 'Unknown',
    lastChecked: 'Last checked',
    refresh: 'Refresh',
    viewDetails: 'View Details',
  },

  languagesPageTitle: 'Available Languages',
  languagesPageDescription: 'Choose your preferred language to access the site in your native language.',
  availableLanguages: 'Available Languages',
  currentLanguage: 'Current Language',
  copyUrl: 'Copy URL',
  urlCopied: 'URL copied to clipboard!',
  selectLanguage: 'Select Language',
    useTool: 'Use Tool',
    open: 'Open',
  
  // ToolLayout privacy notice
  privacyNoticeTitle: '🔒 Privacy Guaranteed',
  privacyNoticeBody: 'All files are processed locally in your browser. Your information is not sent to our servers.',

  // Video to MP3 Converter
  videoToMp3Title: 'Video to MP3 Converter',
  videoToMp3Description: 'Extract audio from videos and convert to MP3 format.',
  videoToMp3: {
    loadingFFmpeg: 'Loading FFmpeg...',
    ffmpegLoadedSuccess: 'FFmpeg loaded successfully!',
    ffmpegLoadError: 'Could not load converter. Try reloading the page.',
    unsupportedFormat: 'Unsupported file format. Please select a valid video.',
    startingConversion: 'Starting conversion...',
    loadingVideo: 'Loading video...',
    readingConvertedFile: 'Reading converted file...',
    conversionCompleted: 'Conversion completed successfully!',
    conversionError: 'Conversion error',
    unknownError: 'Unknown error',
    selectOrDragVideo: 'Select or drag a video',
    supportedFormats: 'Supported formats: MP4, AVI, MOV, WEBM, MKV, FLV, WMV',
    chooseFile: 'Choose File',
    removeFile: 'Remove file',
    conversionSettings: 'Conversion Settings',
    audioQuality: 'Audio Quality',
    audioQualityStandard: '128 kbps (Standard)',
    audioQualityHigh: '192 kbps (High)',
    audioQualityMaximum: '320 kbps (Maximum)',
    sampleRate: 'Sample Rate',
    sampleRateStandard: '44.1 kHz (Standard)',
    sampleRateHigh: '48 kHz',
    convertingToMp3: 'Converting video to MP3...',
    loadingConverter: 'Loading converter...',
    loadingConverterMessage: 'Loading the converter, this may take a few seconds...',
    convertToMp3: 'Convert to MP3',
    conversionCompleted: 'Conversion Completed',
    audioMp3: 'MP3 Audio',
    downloadMp3: 'Download MP3',
    convertAnotherVideo: 'Convert another video',
    noVideoSelected: 'No video selected',
    selectVideoMessage: 'Select a video to extract audio in MP3 format',
    howItWorks: '💡 How it works:',
    executingCommand: 'Executing command',
    downloadStarted: 'Download started',
    converterRestarted: 'Converter restarted',
    qualityStandard: '128 kbps (Standard)',
    qualityHigh: '192 kbps (High)',
    qualityMaximum: '320 kbps (Maximum)',
    convertingVideo: 'Converting video to MP3...',
    selectVideoToExtract: 'Select a video to extract audio in MP3 format',
    howItWorks: 'How it works',
    localProcessing: 'All processing is done locally in your browser',
    noServerUpload: 'Your files are not sent to any server',
    multipleFormats: 'Supports various popular video formats',
    adjustableQuality: 'Adjustable quality for different needs',
    fastSecureProcess: 'Fast and secure process to extract audio from videos'
  },
  wordToPdf: {
    title: 'Word to PDF Converter',
    description: 'Convert Word documents to PDF format',
    selectOrDragWord: 'Select Word document or drag and drop here',
    supportedFormats: 'Supported formats: DOC, DOCX',
    chooseFile: 'Choose Word File',
    documentInfo: 'Document Information',
    titleField: 'Title',
    authorField: 'Author',
    wordsCount: 'words',
    pagesCount: 'pages',
    conversionSettings: 'Conversion Settings',
    showAdvanced: 'Show Advanced',
    hideAdvanced: 'Hide Advanced',
    pageSize: 'Page Size',
    pageSizeA4: 'A4',
    pageSizeLetter: 'Letter',
    pageSizeLegal: 'Legal',
    orientation: 'Orientation',
    orientationPortrait: 'Portrait',
    orientationLandscape: 'Landscape',
    fontFamily: 'Font',
    fontHelvetica: 'Helvetica',
    fontTimesRoman: 'Times Roman',
    fontCourier: 'Courier',
    fontSize: 'Font Size',
    lineSpacing: 'Line Spacing',
    preserveFormatting: 'Preserve original formatting',
    includeImages: 'Include images',
    includeHeaders: 'Include headers',
    includeFooters: 'Include footers',
    numberPages: 'Number pages',
    converting: 'Converting...',
    convertToPdf: 'Convert to PDF',
    convertingWordToPdf: 'Converting Word to PDF...',
    conversionCompleted: 'Conversion completed successfully!',
    conversionError: 'Error during conversion',
    downloadPdf: 'Download PDF',
    convertAnotherDocument: 'Convert Another Document',
    aboutConversion: 'About Word to PDF Conversion',
    conversionTips: 'Conversion Tips',
    tipPreserveFormatting: 'Enable "Preserve formatting" to maintain original document styling',
    tipImageQuality: 'Images are automatically optimized for PDF format',
    tipFontCompatibility: 'Choose standard fonts for better compatibility',
    tipPageSettings: 'Adjust page size and orientation according to your needs',
    invalidFileType: 'Please select only Word files (.docx, .doc, .rtf).',
    fileTooLarge: 'File too large. Limit of 50MB.',
    selectDocument: 'Select Word document',
    dragDropText: 'Drag and drop your Word file here or click to select',
    selectFile: 'Select Word File',
    author: 'Author',
        wordCount: 'Words (est.)',
        pageCount: 'Pages (est.)',
        imagesCount: 'Images',
        timeCount: 'Time',
        convertAnother: 'Convert Another Document',
        aboutFeature1: 'Converts .docx, .doc and .rtf documents to PDF',
        aboutFeature2: 'Preserves formatting, images and document structure',
        aboutFeature3: 'Flexible page and font settings',
        aboutFeature4: 'Support for headers, footers and numbering',
        aboutFeature5: 'Ideal for archiving and sharing',
        tip1: 'Use A4 for standard Brazilian documents',
        tip2: 'Helvetica offers better screen readability',
        tip3: 'Preserve formatting to maintain original appearance',
        tip4: 'Include numbering for long documents',
        tip5: 'Check margins for proper printing'
  },
  unlockPdf: {
    title: 'Unlock PDF',
    description: 'Remove passwords and restrictions from protected PDF documents',
    selectPdfFile: 'Select PDF File',
    dragDropText: 'Drag and drop your protected PDF file here',
    orText: 'or',
    selectFile: 'Select File',
    selectedFile: 'Selected File',
    clear: 'Clear',
    pdfPassword: 'PDF Password',
    enterPassword: 'Enter PDF password',
    unlocking: 'Unlocking...',
    unlockPdf: 'Unlock PDF',
    unlockedPdf: 'PDF Unlocked',
    successMessage: 'PDF unlocked successfully!',
    notProtectedMessage: 'PDF processed (was not protected)',
    fileName: 'File:',
    fileSize: 'Size:',
    pageCount: 'Pages:',
    removedRestrictions: 'Removed restrictions:',
    downloadUnlocked: 'Download Unlocked PDF',
    howItWorks: '🔓 How it works:',
    feature1: '• Removes opening passwords from PDF documents',
    feature2: '• Eliminates printing, copying and editing restrictions',
    feature3: '• Creates a new version of the PDF without protections',
    feature4: '• Maintains all original content and formatting',
    feature5: '• Processing performed locally in the browser',
    important: '⚠️ Important',
    warning1: '• Use only on PDFs you own or have authorization to unlock',
    warning2: '• Respect copyrights and terms of use of documents',
    warning3: '• Some PDFs with advanced encryption may not be unlockable',
    warning4: '• Password is only required for password-protected PDFs',
    warning5: '• Secure processing - passwords are not stored',
    passwordRequired: 'This PDF is password protected. Enter the password to continue.',
    incorrectPassword: 'Incorrect password or PDF cannot be unlocked.',
    processingError: 'Error processing PDF. Check if the file is not corrupted.',
    openingPassword: 'Opening password',
    printingRestrictions: 'Printing restrictions',
    copyingRestrictions: 'Copying restrictions',
    editingRestrictions: 'Editing restrictions',
    annotationRestrictions: 'Annotation restrictions'
  },
};

const TRANSLATIONS: Record<Language, typeof EN_TRANSLATIONS> = {
  en: EN_TRANSLATIONS,
  'pt-BR': {
    ...EN_TRANSLATIONS,
    siteTitle: 'Ferramentas Online Gratuitas',
    siteName: 'Ferramentas Online',
    siteDescription: 'Acesse um conjunto abrangente de ferramentas online gratuitas para edição de PDF, conversão de vídeo, processamento de imagens e geração de códigos QR. Converta, comprima e otimize arquivos com segurança no seu navegador.',
    home: 'Início',
    tools: 'Ferramentas',
    about: 'Sobre',
    contact: 'Contato',
    legal: 'Legal',
    privacyPolicy: 'Política de Privacidade',
    termsOfUse: 'Termos de Uso',
    sitemap: 'Mapa do Site',
    languages: 'Idiomas',
    search: 'Buscar',
    skipToContent: 'Pular para o conteúdo',
    toggleTheme: 'Alternar tema',
    closeMenu: 'Fechar menu',
    openMenu: 'Abrir menu',
    heroTitle: 'Ferramentas Online Gratuitas',
    heroSubtitle: 'Tudo que você precisa em um só lugar',
    heroDescription: 'Acesse uma coleção completa de ferramentas online gratuitas para facilitar seu trabalho e aumentar sua produtividade.',
    searchPlaceholder: 'Buscar ferramentas...',
    allCategories: 'Todas',
    totalTools: 'Total:',
    toolsCounter: 'ferramentas disponíveis',
    footerText: 'Todos os direitos reservados.',
    privacyText: 'Respeitamos sua privacidade.',
    madeWith: 'Feito com',
    by: 'por',
    followUs: 'Siga-nos',
    navigation: 'Navegação',
    notebookTitle: 'Bloco de Notas',
    notebookDescription: 'Escreva e salve suas anotações rapidamente.',

    // Legal page translations
    legalCompanyInfo: 'Informações da Empresa',
    legalCompanyInfoText: 'Muiltools é uma plataforma baseada na web que fornece várias ferramentas e utilitários online para produtividade e conveniência.',
    legalIntellectualProperty: 'Propriedade Intelectual',
    legalIntellectualPropertyText: 'Todo o conteúdo, recursos e funcionalidades deste site são de propriedade da Muiltools e são protegidos por leis internacionais de direitos autorais, marcas registradas e outras leis de propriedade intelectual.',
    legalLiability: 'Limitação de Responsabilidade',
    legalLiabilityText: 'A Muiltools fornece ferramentas e serviços "como estão" sem quaisquer garantias. Não somos responsáveis por quaisquer danos decorrentes do uso de nossos serviços.',
    legalGoverningLaw: 'Lei Aplicável',
    legalGoverningLawText: 'Estes termos legais são regidos e interpretados de acordo com as leis aplicáveis.',
    legalContact: 'Informações de Contato',
    legalContactText: 'Se você tiver alguma dúvida sobre estes termos legais, entre em contato conosco através de nossa página de contato.',

    // Privacy Policy translations
    privacyIntro: 'Introdução',
    privacyIntroText: 'Esta Política de Privacidade descreve como a Muiltools coleta, usa e protege suas informações quando você usa nosso site e serviços.',
    privacyDataCollection: 'Coleta de Dados',
    privacyDataCollectionText: 'Coletamos informações que você nos fornece diretamente, como quando você usa nossas ferramentas, entra em contato conosco ou interage com nosso site.',
    privacyCookies: 'Cookies e Rastreamento',
    privacyCookiesText: 'Usamos cookies e tecnologias similares para melhorar sua experiência, analisar o uso e fornecer conteúdo personalizado.',
    privacyDataUse: 'Como Usamos Seus Dados',
    privacyDataUseText: 'Usamos as informações coletadas para fornecer, manter e melhorar nossos serviços, comunicar com você e garantir a segurança.',
    privacyDataSharing: 'Compartilhamento de Dados',
    privacyDataSharingText: 'Não vendemos, negociamos ou transferimos suas informações pessoais para terceiros sem seu consentimento, exceto conforme descrito nesta política.',
    privacyRights: 'Seus Direitos',
    privacyRightsText: 'Você tem o direito de acessar, atualizar ou excluir suas informações pessoais. Entre em contato conosco se desejar exercer esses direitos.',
    privacyContact: 'Entre em Contato',
    privacyContactText: 'Se você tiver alguma dúvida sobre esta Política de Privacidade, entre em contato conosco através de nossa página de contato.',

    // Terms of Use translations
    termsAcceptance: 'Aceitação dos Termos',
    termsAcceptanceText: 'Ao acessar e usar a Muiltools, você aceita e concorda em estar vinculado aos termos e disposições deste acordo.',
    termsUseOfService: 'Uso do Serviço',
    termsUseOfServiceText: 'Você pode usar nosso serviço apenas para fins legais. Você concorda em não usar o serviço de forma que viole quaisquer leis ou regulamentos aplicáveis.',
    termsUserContent: 'Conteúdo do Usuário',
    termsUserContentText: 'Você mantém a propriedade de qualquer conteúdo que enviar, postar ou exibir no serviço. Você é responsável pelo conteúdo que fornece.',
    termsProhibitedUse: 'Usos Proibidos',
    termsProhibitedUseText: 'Você não pode usar nosso serviço para qualquer propósito ilegal ou não autorizado, para violar quaisquer leis ou para prejudicar ou explorar outros.',
    termsDisclaimer: 'Isenção de Responsabilidade',
    termsDisclaimerText: 'As informações neste site são fornecidas "como estão". Renunciamos a todas as garantias e não fazemos representações sobre a precisão ou confiabilidade do conteúdo.',
    termsModification: 'Modificação dos Termos',
    termsModificationText: 'Reservamo-nos o direito de modificar estes termos a qualquer momento. As alterações entrarão em vigor imediatamente após a publicação no site.',
    termsContact: 'Informações de Contato',
    termsContactText: 'Se você tiver alguma dúvida sobre estes Termos de Uso, entre em contato conosco através de nossa página de contato.',
    notebook: {
      confirmClear: 'Tem certeza de que deseja limpar as anotações?',
      saved: 'Salvo',
      save: 'Salvar',
      download: 'Baixar',
      clear: 'Limpar',
      placeholder: 'Digite suas anotações aqui...',
      characterCount: 'caracteres',
      yourNotes: 'Suas Anotações',
      lastModified: 'Última modificação',
      autoSaveTitle: 'Salvamento Automático',
      autoSaveDescription: 'Suas anotações são salvas automaticamente a cada poucos segundos.',
      privacyTitle: 'Privacidade',
      privacyDescription: 'Todo o conteúdo é armazenado apenas no seu navegador.',
      exportTitle: 'Exportar',
      exportDescription: 'Baixe suas anotações como arquivo de texto.',
    },
    languagesPageTitle: 'Idiomas Disponíveis',
    languagesPageDescription: 'Escolha seu idioma preferido para acessar o site em sua língua nativa.',
    availableLanguages: 'Idiomas Disponíveis',
    currentLanguage: 'Idioma Atual',
    copyUrl: 'Copiar URL',
    urlCopied: 'URL copiada para a área de transferência!',
    selectLanguage: 'Selecionar Idioma',
    useTool: 'Usar Ferramenta',
    open: 'Abrir',
    
    // ToolLayout privacy notice
    privacyNoticeTitle: '🔒 Privacidade Garantida',
      privacyNoticeBody: 'Todos os arquivos são processados localmente no seu navegador. Suas informações não são enviadas para nossos servidores.',

      // Video to MP3 Converter
      videoToMp3Title: 'Conversor de Vídeo para MP3',
      videoToMp3Description: 'Extraia áudio de vídeos e converta para formato MP3.',
      videoToMp3: {
        loadingFFmpeg: 'Carregando FFmpeg...',
        ffmpegLoadedSuccess: 'FFmpeg carregado com sucesso!',
        ffmpegLoadError: 'Não foi possível carregar o conversor. Tente recarregar a página.',
        unsupportedFormat: 'Formato de arquivo não suportado. Por favor, selecione um vídeo válido.',
        startingConversion: 'Iniciando conversão...',
        loadingVideo: 'Carregando vídeo...',
        readingConvertedFile: 'Lendo arquivo convertido...',
        conversionCompleted: 'Conversão concluída com sucesso!',
        conversionError: 'Erro na conversão',
        unknownError: 'Erro desconhecido',
        selectOrDragVideo: 'Selecione ou arraste um vídeo',
        supportedFormats: 'Formatos suportados: MP4, AVI, MOV, WEBM, MKV, FLV, WMV',
        chooseFile: 'Escolher Arquivo',
        removeFile: 'Remover arquivo',
        conversionSettings: 'Configurações de Conversão',
        audioQuality: 'Qualidade do Áudio',
        audioQualityStandard: '128 kbps (Padrão)',
        audioQualityHigh: '192 kbps (Alta)',
        audioQualityMaximum: '320 kbps (Máxima)',
        sampleRate: 'Taxa de Amostragem',
        sampleRateStandard: '44.1 kHz (Padrão)',
        sampleRateHigh: '48 kHz',
        convertingToMp3: 'Convertendo vídeo para MP3...',
        loadingConverter: 'Carregando conversor...',
        loadingConverterMessage: 'Carregando o conversor, isso pode levar alguns segundos...',
        convertToMp3: 'Converter para MP3',
        audioMp3: 'Áudio MP3',
        downloadMp3: 'Baixar MP3',
        convertAnotherVideo: 'Converter outro vídeo',
        noVideoSelected: 'Nenhum vídeo selecionado',
        selectVideoMessage: 'Selecione um vídeo para extrair o áudio em formato MP3',
        howItWorks: 'Como funciona',
        executingCommand: 'Executando comando',
        downloadStarted: 'Download iniciado',
        converterRestarted: 'Conversor reiniciado',
        qualityStandard: '128 kbps (Padrão)',
        qualityHigh: '192 kbps (Alta)',
        qualityMaximum: '320 kbps (Máxima)',
        convertingVideo: 'Convertendo vídeo para MP3...',
        selectVideoToExtract: 'Selecione um vídeo para extrair o áudio em formato MP3',
        localProcessing: 'Todo o processamento é feito localmente no seu navegador',
        noServerUpload: 'Seus arquivos não são enviados para nenhum servidor'
      },
      wordToPdf: {
        title: 'Conversor de Word para PDF',
        description: 'Converta documentos Word para formato PDF',
        selectOrDragWord: 'Selecione o documento Word ou arraste e solte aqui',
        supportedFormats: 'Formatos suportados: DOC, DOCX',
        chooseFile: 'Escolher Arquivo Word',
        documentInfo: 'Informações do Documento',
        titleField: 'Título',
        authorField: 'Autor',
        wordsCount: 'palavras',
        pagesCount: 'páginas',
        conversionSettings: 'Configurações de Conversão',
        showAdvanced: 'Mostrar Avançadas',
        hideAdvanced: 'Ocultar Avançadas',
        pageSize: 'Tamanho da Página',
        pageSizeA4: 'A4',
        pageSizeLetter: 'Letter',
        pageSizeLegal: 'Legal',
        orientation: 'Orientação',
        orientationPortrait: 'Retrato',
        orientationLandscape: 'Paisagem',
        fontFamily: 'Fonte',
        fontHelvetica: 'Helvetica',
        fontTimesRoman: 'Times Roman',
        fontCourier: 'Courier',
        fontSize: 'Tamanho da Fonte',
        lineSpacing: 'Espaçamento de Linha',
        preserveFormatting: 'Preservar formatação original',
        includeImages: 'Incluir imagens',
        includeHeaders: 'Incluir cabeçalhos',
        includeFooters: 'Incluir rodapés',
        numberPages: 'Numerar páginas',
        converting: 'Convertendo...',
        convertToPdf: 'Converter para PDF',
        convertingWordToPdf: 'Convertendo Word para PDF...',
        conversionCompleted: 'Conversão concluída com sucesso!',
        conversionError: 'Erro durante a conversão',
        downloadPdf: 'Baixar PDF',
        convertAnotherDocument: 'Converter Outro Documento',
        aboutConversion: 'Sobre a Conversão Word para PDF',
        conversionTips: 'Dicas de Conversão',
        tipPreserveFormatting: 'Ative "Preservar formatação" para manter o estilo original do documento',
        tipImageQuality: 'As imagens são automaticamente otimizadas para o formato PDF',
        tipFontCompatibility: 'Escolha fontes padrão para melhor compatibilidade',
        tipPageSettings: 'Ajuste o tamanho e orientação da página conforme suas necessidades',
        invalidFileType: 'Por favor, selecione apenas arquivos Word (.docx, .doc, .rtf).',
        fileTooLarge: 'Arquivo muito grande. Limite de 50MB.',
        selectDocument: 'Selecione o documento Word',
        dragDropText: 'Arraste e solte seu arquivo Word aqui ou clique para selecionar',
        selectFile: 'Selecionar Arquivo Word',
        author: 'Autor',
        wordCount: 'Palavras (est.)',
        pageCount: 'Páginas (est.)',
        imagesCount: 'Imagens',
        timeCount: 'Tempo',
        convertAnother: 'Converter Outro Documento',
        aboutFeature1: 'Converte documentos .docx, .doc e .rtf para PDF',
        aboutFeature2: 'Preserva formatação, imagens e estrutura do documento',
        aboutFeature3: 'Configurações flexíveis de página e fonte',
        aboutFeature4: 'Suporte a cabeçalhos, rodapés e numeração',
        aboutFeature5: 'Ideal para arquivamento e compartilhamento',
        tip1: 'Use A4 para documentos padrão brasileiros',
        tip2: 'Helvetica oferece melhor legibilidade em tela',
        tip3: 'Preserve formatação para manter aparência original',
        tip4: 'Inclua numeração para documentos longos',
        tip5: 'Verifique margens para impressão adequada'
      },
      unlockPdf: {
        title: 'Desbloquear PDF',
        description: 'Remova senhas e restrições de arquivos PDF protegidos',
        selectFile: 'Selecionar Arquivo PDF',
        dragDropText: 'Arraste e solte seu arquivo PDF protegido aqui',
        selectFileButton: 'Selecionar Arquivo',
        selectedFile: 'Arquivo Selecionado',
        clear: 'Limpar',
        pdfPassword: 'Senha do PDF',
        enterPassword: 'Digite a senha do PDF',
        unlocking: 'Desbloqueando...',
        unlockPdf: 'Desbloquear PDF',
        pdfUnlocked: 'PDF Desbloqueado',
        unlockSuccess: 'PDF desbloqueado com sucesso!',
        processedNotProtected: 'PDF processado (não estava protegido)',
        fileName: 'Arquivo:',
        fileSize: 'Tamanho:',
        pageCount: 'Páginas:',
        restrictionsRemoved: 'Restrições removidas:',
        downloadUnlocked: 'Baixar PDF Desbloqueado',
        howItWorks: 'Como funciona:',
        important: 'Importante',
        passwordProtected: 'Este PDF está protegido por senha. Digite a senha para continuar.',
        processingError: 'Erro ao processar o PDF. Verifique se o arquivo não está corrompido.',
        invalidFileType: 'Por favor, selecione apenas arquivos PDF.',
        fileTooLarge: 'Arquivo muito grande. Limite de 50MB.',
        openingPassword: 'Senha de abertura',
        printRestrictions: 'Restrições de impressão',
        copyRestrictions: 'Restrições de cópia',
        editRestrictions: 'Restrições de edição',
        annotationRestrictions: 'Restrições de anotação',
        feature1: 'Remove senhas de abertura de documentos PDF',
        feature2: 'Elimina restrições de impressão, cópia e edição',
        feature3: 'Mantém a qualidade original do documento',
        feature4: 'Processamento seguro e privado no navegador',
        feature5: 'Suporte a diferentes tipos de proteção PDF',
        warning1: 'Use apenas com PDFs que você possui ou tem autorização',
        warning2: 'Respeite os direitos autorais e termos de uso',
        warning3: 'Alguns PDFs podem ter proteções não removíveis',
        warning4: 'O processo é irreversível - faça backup se necessário',
        warning5: 'Processamento seguro - senhas não são armazenadas'
      },

      pdfaValidatorTitle: 'Validador PDF/A',
      pdfaValidatorDescription: 'Valide arquivos PDF para conformidade e padrões PDF/A.',
      pdfaValidator: {
        selectFile: 'Selecione o arquivo',
        selectFileTitle: 'Selecionar Arquivo',
        selectButton: 'Selecionar Arquivo',
        dragDrop: 'Arraste e solte seu arquivo PDF aqui',
        dragDropHint: 'Arraste e solte seu arquivo PDF aqui',
        onlyPdfSupported: 'Apenas arquivos PDF são suportados',
        onlyPdfHint: 'Apenas arquivos PDF são suportados',
        pdfOnlyAlert: 'Apenas arquivos PDF são suportados',
        validating: 'Validando...',
        checkingCompliance: 'Verificando conformidade PDF/A',
        checkingPdfa: 'Verificando conformidade PDF/A',
        results: 'Resultados',
        resultTitle: 'Resultados',
        clear: 'Limpar',
        file: 'Arquivo:',
        fileLabel: 'Arquivo:',
        size: 'Tamanho:',
        sizeLabel: 'Tamanho:',
        validatedAt: 'Validado em',
        valid: 'Válido',
        invalid: 'Inválido',
        detectedLevel: 'Nível detectado',
        issues: 'Problemas',
        warnings: 'Avisos',
        aboutTitle: 'Sobre',
        aboutItems: [
          'PDF/A é um formato de arquivo para preservação de longo prazo',
          'Garante que documentos permaneçam acessíveis ao longo do tempo',
          'Remove dependências de recursos externos',
          'Padroniza fontes e espaços de cores'
        ],
        tipsTitle: 'Dicas',
        tipsItems: [
          'Use fontes incorporadas para melhor compatibilidade',
          'Evite transparência e gráficos complexos',
          'Inclua metadados adequados e estrutura do documento',
          'Teste com múltiplos validadores para precisão'
        ],
        documentTitleUndefined: 'Título do documento não definido',
        documentCreatorUndefined: 'Criador do documento não definido',
        documentProducerUndefined: 'Produtor do documento não definido',
        pdfaMetadataNotFound: 'Metadados PDF/A não encontrados no documento',
        noComplianceIdentifiers: 'Documento não contém identificadores de conformidade PDF/A',
        keywordsRecommendedPdfa1b: 'Palavras-chave recomendadas para PDF/A-1B',
        subjectRecommendedPdfa2b3b: 'Assunto recomendado para PDF/A-2B ou PDF/A-3B',
        documentNoPages: 'Documento PDF não contém páginas',
         noPagesFound: 'Documento PDF não contém páginas',
         errorProcessingPdf: 'Erro ao processar o arquivo PDF',
         processingError: 'Erro ao processar o arquivo PDF',
         fileCorruptedOrInvalid: 'Arquivo pode estar corrompido ou não ser um PDF válido',
         corruptedFileError: 'Arquivo pode estar corrompido ou não ser um PDF válido'
      },
      qrGenerator: {
        inputPlaceholder: 'Digite texto ou URL',
        generate: 'Gerar QR Code',
        download: 'Baixar QR Code',
        size: 'Tamanho',
        errorCorrection: 'Correção de Erro',
        low: 'Baixa',
        medium: 'Média',
        quartile: 'Quartil',
        high: 'Alta',
        enterContent: 'Por favor, digite o conteúdo para gerar o QR code',
        errorGenerating: 'Erro ao gerar QR code',
        settings: 'Configurações',
        contentType: 'Tipo de Conteúdo',
        content: 'Conteúdo',
        color: 'Cor',
        preview: 'Visualização',
        generated: 'QR Code Gerado',
        previewText: 'O QR Code aparecerá aqui',
        contentTypes: {
          text: 'Texto',
          url: 'URL',
          wifi: 'Wi-Fi',
          vcard: 'Cartão de Visita',
          sms: 'SMS',
        },
        placeholders: {
          text: 'Digite seu texto aqui...',
          url: 'https://exemplo.com',
          wifi: 'WIFI:T:WPA;S:NomeRede;P:senha;;',
          vcard: 'BEGIN:VCARD\nVERSION:3.0\nFN:Nome Completo\nORG:Empresa\nTEL:+55123456789\nEMAIL:email@exemplo.com\nEND:VCARD',
          sms: 'SMSTO:+55123456789:Sua mensagem aqui',
        },
      },
  },
  es: {
    ...EN_TRANSLATIONS,
    siteTitle: 'Herramientas Online Gratuitas',
    siteName: 'Herramientas Online',
    siteDescription: 'Accede a un conjunto completo de herramientas online gratuitas para edición de PDF, conversión de video, procesamiento de imágenes y generación de códigos QR. Convierte, comprime y optimiza archivos de forma segura en tu navegador.',
    home: 'Inicio',
    tools: 'Herramientas',
    about: 'Acerca de',
    contact: 'Contacto',
    legal: 'Legal',
    privacyPolicy: 'Política de Privacidad',
    termsOfUse: 'Términos de Uso',
    sitemap: 'Mapa del Sitio',
    languages: 'Idiomas',
    skipToContent: 'Saltar al contenido',
    toggleTheme: 'Cambiar tema',
    closeMenu: 'Cerrar menú',
    openMenu: 'Abrir menú',
    search: 'Buscar',
    heroTitle: 'Herramientas Online Gratuitas',
    heroSubtitle: 'Todo lo que necesitas en un solo lugar',
    heroDescription: 'Accede a una colección completa de herramientas online gratuitas para facilitar tu trabajo y aumentar tu productividad.',
    searchPlaceholder: 'Buscar herramientas...',
    allCategories: 'Todas',
    totalTools: 'Total:',
    toolsCounter: 'herramientas disponibles',
    footerText: 'Todos los derechos reservados.',
    privacyText: 'Respetamos tu privacidad.',
    madeWith: 'Hecho con',
    by: 'por',
    followUs: 'Síguenos',
    navigation: 'Navegación',
    notebookTitle: 'Bloc de Notas',
    notebookDescription: 'Escribe y guarda tus notas rápidamente.',

    // Legal page translations
    legalCompanyInfo: 'Información de la Empresa',
    legalCompanyInfoText: 'Muiltools es una plataforma basada en web que proporciona varias herramientas y utilidades en línea para productividad y conveniencia.',
    legalIntellectualProperty: 'Propiedad Intelectual',
    legalIntellectualPropertyText: 'Todo el contenido, características y funcionalidad de este sitio web son propiedad de Muiltools y están protegidos por leyes internacionales de derechos de autor, marcas registradas y otras leyes de propiedad intelectual.',
    legalLiability: 'Limitación de Responsabilidad',
    legalLiabilityText: 'Muiltools proporciona herramientas y servicios "tal como están" sin garantías. No somos responsables de ningún daño que surja del uso de nuestros servicios.',
    legalGoverningLaw: 'Ley Aplicable',
    legalGoverningLawText: 'Estos términos legales se rigen e interpretan de acuerdo con las leyes aplicables.',
    legalContact: 'Información de Contacto',
    legalContactText: 'Si tienes alguna pregunta sobre estos términos legales, contáctanos a través de nuestra página de contacto.',

    // Privacy Policy translations
    privacyIntro: 'Introducción',
    privacyIntroText: 'Esta Política de Privacidad describe cómo Muiltools recopila, usa y protege tu información cuando usas nuestro sitio web y servicios.',
    privacyDataCollection: 'Recopilación de Datos',
    privacyDataCollectionText: 'Recopilamos información que nos proporcionas directamente, como cuando usas nuestras herramientas, nos contactas o interactúas con nuestro sitio web.',
    privacyCookies: 'Cookies y Seguimiento',
    privacyCookiesText: 'Utilizamos cookies y tecnologías similares para mejorar tu experiencia, analizar el uso y proporcionar contenido personalizado.',
    privacyDataUse: 'Cómo Usamos Tus Datos',
    privacyDataUseText: 'Utilizamos la información recopilada para proporcionar, mantener y mejorar nuestros servicios, comunicarnos contigo y garantizar la seguridad.',
    privacyDataSharing: 'Compartir Datos',
    privacyDataSharingText: 'No vendemos, intercambiamos o transferimos tu información personal a terceros sin tu consentimiento, excepto como se describe en esta política.',
    privacyRights: 'Tus Derechos',
    privacyRightsText: 'Tienes derecho a acceder, actualizar o eliminar tu información personal. Contáctanos si deseas ejercer estos derechos.',
    privacyContact: 'Contáctanos',
    privacyContactText: 'Si tienes alguna pregunta sobre esta Política de Privacidad, contáctanos a través de nuestra página de contacto.',

    // Terms of Use translations
    termsAcceptance: 'Aceptación de Términos',
    termsAcceptanceText: 'Al acceder y usar Muiltools, aceptas y acuerdas estar sujeto a los términos y disposiciones de este acuerdo.',
    termsUseOfService: 'Uso del Servicio',
    termsUseOfServiceText: 'Puedes usar nuestro servicio solo para propósitos legales. Acuerdas no usar el servicio de manera que viole cualquier ley o regulación aplicable.',
    termsUserContent: 'Contenido del Usuario',
    termsUserContentText: 'Mantienes la propiedad de cualquier contenido que envíes, publiques o muestres en el servicio. Eres responsable del contenido que proporcionas.',
    termsProhibitedUse: 'Usos Prohibidos',
    termsProhibitedUseText: 'No puedes usar nuestro servicio para ningún propósito ilegal o no autorizado, para violar cualquier ley o para dañar o explotar a otros.',
    termsDisclaimer: 'Descargo de Responsabilidad',
    termsDisclaimerText: 'La información en este sitio web se proporciona "tal como está". Renunciamos a todas las garantías y no hacemos representaciones sobre la precisión o confiabilidad del contenido.',
    termsModification: 'Modificación de Términos',
    termsModificationText: 'Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios serán efectivos inmediatamente después de su publicación en el sitio web.',
    termsContact: 'Información de Contacto',
    termsContactText: 'Si tienes alguna pregunta sobre estos Términos de Uso, contáctanos a través de nuestra página de contacto.',
    notebook: {
      confirmClear: '¿Estás seguro de que quieres limpiar las notas?',
      saved: 'Guardado',
      save: 'Guardar',
      download: 'Descargar',
      clear: 'Limpiar',
      placeholder: 'Escribe tus notas aquí...',
      characterCount: 'caracteres',
      yourNotes: 'Tus Notas',
      lastModified: 'Última modificación',
      autoSaveTitle: 'Guardado Automático',
      autoSaveDescription: 'Tus notas se guardan automáticamente cada pocos segundos.',
      privacyTitle: 'Privacidad',
      privacyDescription: 'Todo el contenido se almacena solo en tu navegador.',
      exportTitle: 'Exportar',
      exportDescription: 'Descarga tus notas como archivo de texto.',
    },
    languagesPageTitle: 'Idiomas Disponibles',
    languagesPageDescription: 'Elige tu idioma preferido para acceder al sitio en tu lengua nativa.',
    availableLanguages: 'Idiomas Disponibles',
    currentLanguage: 'Idioma Actual',
    copyUrl: 'Copiar URL',
    urlCopied: '¡URL copiada al portapapeles!',
    selectLanguage: 'Seleccionar Idioma',
  },
  zh: {
    ...EN_TRANSLATIONS,
    siteTitle: '免费在线工具',
    siteName: '在线工具',
    siteDescription: '访问全面的免费在线工具套件，用于PDF编辑、视频转换、图像处理和二维码生成。在您的浏览器中安全地转换、压缩和优化文件。',
    home: '首页',
    tools: '工具',
    about: '关于',
    contact: '联系',
    privacyPolicy: '隐私政策',
    termsOfUse: '使用条款',
    sitemap: '网站地图',
    languages: '语言',
    heroTitle: '免费在线工具',
    heroSubtitle: '您需要的一切都在这里',
    heroDescription: '访问完整的免费在线工具集合，以促进您的工作并提高生产力。',
    searchPlaceholder: '搜索工具...',
    allCategories: '全部',
    totalTools: '总计：',
    toolsCounter: '可用工具',
    notebookTitle: '记事本',
    notebookDescription: '快速编写和保存您的笔记。',
    notebook: {
      confirmClear: '您确定要清除笔记吗？',
      saved: '已保存',
      save: '保存',
      download: '下载',
      clear: '清除',
      placeholder: '在此输入您的笔记...',
      characterCount: '字符',
      yourNotes: '您的笔记',
      lastModified: '最后修改',
      autoSaveTitle: '自动保存',
      autoSaveDescription: '您的笔记每隔几秒钟自动保存。',
      privacyTitle: '隐私',
      privacyDescription: '所有内容仅存储在您的浏览器中。',
      exportTitle: '导出',
      exportDescription: '将您的笔记下载为文本文件。',
    },
    languagesPageTitle: '可用语言',
    languagesPageDescription: '选择您的首选语言以使用您的母语访问网站。',
    availableLanguages: '可用语言',
    currentLanguage: '当前语言',
    copyUrl: '复制URL',
    urlCopied: 'URL已复制到剪贴板！',
    selectLanguage: '选择语言',
  },
  hi: {
    ...EN_TRANSLATIONS,
    siteTitle: 'मुफ्त ऑनलाइन टूल्स',
    siteName: 'ऑनलाइन टूल्स',
    siteDescription: 'PDF संपादन, वीडियो रूपांतरण, छवि प्रसंस्करण और QR कोड जेनरेशन के लिए मुफ्त ऑनलाइन टूल्स के व्यापक सूट तक पहुंच प्राप्त करें। अपने ब्राउज़र में सुरक्षित रूप से फाइलों को कन्वर्ट, कंप्रेस और ऑप्टिमाइज़ करें।',
    home: 'होम',
    tools: 'टूल्स',
    about: 'के बारे में',
    contact: 'संपर्क',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfUse: 'उपयोग की शर्तें',
    sitemap: 'साइटमैप',
    languages: 'भाषाएं',
    heroTitle: 'मुफ्त ऑनलाइन टूल्स',
    heroSubtitle: 'आपको जो कुछ भी चाहिए वह एक ही जगह',
    heroDescription: 'अपने काम को सुविधाजनक बनाने और उत्पादकता बढ़ाने के लिए मुफ्त ऑनलाइन टूल्स के पूर्ण संग्रह तक पहुंच प्राप्त करें।',
    searchPlaceholder: 'टूल्स खोजें...',
    allCategories: 'सभी',
    totalTools: 'कुल:',
    toolsCounter: 'उपलब्ध टूल्स',
    notebookTitle: 'नोटपैड',
    notebookDescription: 'अपने नोट्स को जल्दी लिखें और सेव करें।',
    notebook: {
      confirmClear: 'क्या आप वाकई नोट्स को साफ़ करना चाहते हैं?',
      saved: 'सेव किया गया',
      save: 'सेव करें',
      download: 'डाउनलोड',
      clear: 'साफ़ करें',
      placeholder: 'यहाँ अपने नोट्स टाइप करें...',
      characterCount: 'अक्षर',
      yourNotes: 'आपके नोट्स',
      lastModified: 'अंतिम संशोधन',
      autoSaveTitle: 'ऑटो सेव',
      autoSaveDescription: 'आपके नोट्स हर कुछ सेकंड में स्वचालित रूप से सेव हो जाते हैं।',
      privacyTitle: 'गोपनीयता',
      privacyDescription: 'सभी सामग्री केवल आपके ब्राउज़र में संग्रहीत है।',
      exportTitle: 'निर्यात',
      exportDescription: 'अपने नोट्स को टेक्स्ट फाइल के रूप में डाउनलोड करें।',
    },
    languagesPageTitle: 'उपलब्ध भाषाएं',
    languagesPageDescription: 'अपनी मातृभाषा में साइट तक पहुंचने के लिए अपनी पसंदीदा भाषा चुनें।',
    availableLanguages: 'उपलब्ध भाषाएं',
    currentLanguage: 'वर्तमान भाषा',
    copyUrl: 'URL कॉपी करें',
    urlCopied: 'URL क्लिपबोर्ड में कॉपी किया गया!',
    selectLanguage: 'भाषा चुनें',
  },
  ar: {
    ...EN_TRANSLATIONS,
    siteTitle: 'أدوات مجانية عبر الإنترنت',
    siteName: 'أدوات عبر الإنترنت',
    siteDescription: 'الوصول إلى مجموعة شاملة من الأدوات المجانية عبر الإنترنت لتحرير PDF وتحويل الفيديو ومعالجة الصور وإنشاء رموز QR. قم بتحويل وضغط وتحسين الملفات بأمان في متصفحك.',
    home: 'الرئيسية',
    tools: 'الأدوات',
    about: 'حول',
    contact: 'اتصل',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfUse: 'شروط الاستخدام',
    sitemap: 'خريطة الموقع',
    languages: 'اللغات',
    heroTitle: 'أدوات مجانية عبر الإنترنت',
    heroSubtitle: 'كل ما تحتاجه في مكان واحد',
    heroDescription: 'الوصول إلى مجموعة كاملة من الأدوات المجانية عبر الإنترنت لتسهيل عملك وزيادة إنتاجيتك.',
    searchPlaceholder: 'البحث عن الأدوات...',
    allCategories: 'الكل',
    totalTools: 'المجموع:',
    toolsCounter: 'أدوات متاحة',
    notebookTitle: 'المفكرة',
    notebookDescription: 'اكتب واحفظ ملاحظاتك بسرعة.',
    notebook: {
      confirmClear: 'هل أنت متأكد من أنك تريد مسح الملاحظات؟',
      saved: 'محفوظ',
      save: 'حفظ',
      download: 'تحميل',
      clear: 'مسح',
      placeholder: 'اكتب ملاحظاتك هنا...',
      characterCount: 'أحرف',
      yourNotes: 'ملاحظاتك',
      lastModified: 'آخر تعديل',
      autoSaveTitle: 'الحفظ التلقائي',
      autoSaveDescription: 'يتم حفظ ملاحظاتك تلقائياً كل بضع ثوانٍ.',
      privacyTitle: 'الخصوصية',
      privacyDescription: 'يتم تخزين جميع المحتويات في متصفحك فقط.',
      exportTitle: 'تصدير',
      exportDescription: 'قم بتنزيل ملاحظاتك كملف نصي.',
    },
    languagesPageTitle: 'اللغات المتاحة',
    languagesPageDescription: 'اختر لغتك المفضلة للوصول إلى الموقع بلغتك الأم.',
    availableLanguages: 'اللغات المتاحة',
    currentLanguage: 'اللغة الحالية',
    copyUrl: 'نسخ الرابط',
    urlCopied: 'تم نسخ الرابط إلى الحافظة!',
    selectLanguage: 'اختيار اللغة',
  },
  bn: {
    ...EN_TRANSLATIONS,
    siteTitle: 'বিনামূল্যে অনলাইন টুলস',
    siteName: 'অনলাইন টুলস',
    siteDescription: 'PDF সম্পাদনা, ভিডিও রূপান্তর, ছবি প্রক্রিয়াকরণ এবং QR কোড তৈরির জন্য বিনামূল্যে অনলাইন টুলসের একটি বিস্তৃত সংগ্রহ অ্যাক্সেস করুন। আপনার ব্রাউজারে নিরাপদে ফাইল রূপান্তর, সংকুচিত এবং অপ্টিমাইজ করুন।',
    home: 'হোম',
    tools: 'টুলস',
    about: 'সম্পর্কে',
    contact: 'যোগাযোগ',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsOfUse: 'ব্যবহারের শর্তাবলী',
    sitemap: 'সাইটম্যাপ',
    languages: 'ভাষা',
    heroTitle: 'বিনামূল্যে অনলাইন টুলস',
    heroSubtitle: 'আপনার প্রয়োজনীয় সবকিছু একই জায়গায়',
    heroDescription: 'আপনার কাজ সহজ করতে এবং উৎপাদনশীলতা বৃদ্ধি করতে বিনামূল্যে অনলাইন টুলসের সম্পূর্ণ সংগ্রহ অ্যাক্সেস করুন।',
    searchPlaceholder: 'টুলস খুঁজুন...',
    allCategories: 'সব',
    totalTools: 'মোট:',
    toolsCounter: 'টুলস উপলব্ধ',
    notebookTitle: 'নোটপ্যাড',
    notebookDescription: 'দ্রুত আপনার নোট লিখুন এবং সংরক্ষণ করুন।',
    notebook: {
      confirmClear: 'আপনি কি নিশ্চিত যে আপনি নোটগুলি মুছে ফেলতে চান?',
      saved: 'সংরক্ষিত',
      save: 'সংরক্ষণ',
      download: 'ডাউনলোড',
      clear: 'মুছুন',
      placeholder: 'এখানে আপনার নোট টাইপ করুন...',
      characterCount: 'অক্ষর',
      yourNotes: 'আপনার নোট',
      lastModified: 'শেষ পরিবর্তন',
      autoSaveTitle: 'অটো সেভ',
      autoSaveDescription: 'আপনার নোটগুলি প্রতি কয়েক সেকেন্ডে স্বয়ংক্রিয়ভাবে সংরক্ষিত হয়।',
      privacyTitle: 'গোপনীয়তা',
      privacyDescription: 'সমস্ত বিষয়বস্তু শুধুমাত্র আপনার ব্রাউজারে সংরক্ষিত।',
      exportTitle: 'রপ্তানি',
      exportDescription: 'আপনার নোটগুলি একটি টেক্সট ফাইল হিসাবে ডাউনলোড করুন।',
    },
    languagesPageTitle: 'উপলব্ধ ভাষা',
    languagesPageDescription: 'আপনার মাতৃভাষায় সাইট অ্যাক্সেস করতে আপনার পছন্দের ভাষা বেছে নিন।',
    availableLanguages: 'উপলব্ধ ভাষা',
    currentLanguage: 'বর্তমান ভাষা',
    copyUrl: 'URL কপি করুন',
    urlCopied: 'URL ক্লিপবোর্ডে কপি করা হয়েছে!',
    selectLanguage: 'ভাষা নির্বাচন করুন',
  },
  ru: {
    ...EN_TRANSLATIONS,
    siteTitle: 'Бесплатные онлайн инструменты',
    siteName: 'Онлайн инструменты',
    siteDescription: 'Получите доступ к полному набору бесплатных онлайн инструментов для редактирования PDF, конвертации видео, обработки изображений и генерации QR-кодов. Конвертируйте, сжимайте и оптимизируйте файлы безопасно в вашем браузере.',
    home: 'Главная',
    tools: 'Инструменты',
    about: 'О нас',
    contact: 'Контакты',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfUse: 'Условия использования',
    sitemap: 'Карта сайта',
    languages: 'Языки',
    heroTitle: 'Бесплатные онлайн инструменты',
    heroSubtitle: 'Всё что нужно в одном месте',
    heroDescription: 'Получите доступ к полной коллекции бесплатных онлайн инструментов для облегчения работы и повышения продуктивности.',
    searchPlaceholder: 'Поиск инструментов...',
    allCategories: 'Все',
    totalTools: 'Всего:',
    toolsCounter: 'инструментов доступно',
    notebookTitle: 'Блокнот',
    notebookDescription: 'Быстро записывайте и сохраняйте свои заметки.',
    notebook: {
      confirmClear: 'Вы уверены, что хотите очистить заметки?',
      saved: 'Сохранено',
      save: 'Сохранить',
      download: 'Скачать',
      clear: 'Очистить',
      placeholder: 'Введите ваши заметки здесь...',
      characterCount: 'символов',
      yourNotes: 'Ваши заметки',
      lastModified: 'Последнее изменение',
      autoSaveTitle: 'Автосохранение',
      autoSaveDescription: 'Ваши заметки автоматически сохраняются каждые несколько секунд.',
      privacyTitle: 'Конфиденциальность',
      privacyDescription: 'Весь контент хранится только в вашем браузере.',
      exportTitle: 'Экспорт',
      exportDescription: 'Скачайте ваши заметки как текстовый файл.',
    },
    languagesPageTitle: 'Доступные языки',
    languagesPageDescription: 'Выберите предпочитаемый язык для доступа к сайту на вашем родном языке.',
    availableLanguages: 'Доступные языки',
    currentLanguage: 'Текущий язык',
    copyUrl: 'Копировать URL',
    urlCopied: 'URL скопирован в буфер обмена!',
    selectLanguage: 'Выбрать язык',
  },
  ja: {
    ...EN_TRANSLATIONS,
    siteTitle: '無料オンラインツール',
    siteName: 'オンラインツール',
    siteDescription: 'PDF編集、動画変換、画像処理、QRコード生成のための包括的な無料オンラインツールスイートにアクセスしてください。ブラウザで安全にファイルを変換、圧縮、最適化できます。',
    home: 'ホーム',
    tools: 'ツール',
    about: 'について',
    contact: 'お問い合わせ',
    privacyPolicy: 'プライバシーポリシー',
    termsOfUse: '利用規約',
    sitemap: 'サイトマップ',
    languages: '言語',
    heroTitle: '無料オンラインツール',
    heroSubtitle: '必要なものすべてが一箇所に',
    heroDescription: '作業を効率化し、生産性を向上させるための無料オンラインツールの完全なコレクションにアクセスしてください。',
    searchPlaceholder: 'ツールを検索...',
    allCategories: 'すべて',
    totalTools: '合計:',
    toolsCounter: 'ツールが利用可能',
    notebookTitle: 'メモ帳',
    notebookDescription: 'メモを素早く書いて保存します。',
    notebook: {
      confirmClear: 'メモをクリアしてもよろしいですか？',
      saved: '保存済み',
      save: '保存',
      download: 'ダウンロード',
      clear: 'クリア',
      placeholder: 'ここにメモを入力してください...',
      characterCount: '文字',
      yourNotes: 'あなたのメモ',
      lastModified: '最終更新',
      autoSaveTitle: '自動保存',
      autoSaveDescription: 'メモは数秒ごとに自動的に保存されます。',
      privacyTitle: 'プライバシー',
      privacyDescription: 'すべてのコンテンツはブラウザにのみ保存されます。',
      exportTitle: 'エクスポート',
      exportDescription: 'メモをテキストファイルとしてダウンロードします。',
    },
    languagesPageTitle: '利用可能な言語',
    languagesPageDescription: '母国語でサイトにアクセスするために、お好みの言語を選択してください。',
    availableLanguages: '利用可能な言語',
    currentLanguage: '現在の言語',
    copyUrl: 'URLをコピー',
    urlCopied: 'URLがクリップボードにコピーされました！',
    selectLanguage: '言語を選択',
  },
  de: {
    ...EN_TRANSLATIONS,
    siteTitle: 'Kostenlose Online-Tools',
    siteName: 'Online-Tools',
    siteDescription: 'Zugriff auf eine umfassende Suite kostenloser Online-Tools für PDF-Bearbeitung, Videokonvertierung, Bildverarbeitung und QR-Code-Generierung. Konvertieren, komprimieren und optimieren Sie Dateien sicher in Ihrem Browser.',
    home: 'Startseite',
    tools: 'Tools',
    about: 'Über uns',
    contact: 'Kontakt',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfUse: 'Nutzungsbedingungen',
    sitemap: 'Sitemap',
    languages: 'Sprachen',
    heroTitle: 'Kostenlose Online-Tools',
    heroSubtitle: 'Alles was Sie brauchen an einem Ort',
    heroDescription: 'Zugriff auf eine vollständige Sammlung kostenloser Online-Tools zur Erleichterung Ihrer Arbeit und Steigerung Ihrer Produktivität.',
    searchPlaceholder: 'Tools suchen...',
    allCategories: 'Alle',
    totalTools: 'Gesamt:',
    toolsCounter: 'Tools verfügbar',
    notebookTitle: 'Notizblock',
    notebookDescription: 'Schreiben und speichern Sie Ihre Notizen schnell.',
    notebook: {
      confirmClear: 'Sind Sie sicher, dass Sie die Notizen löschen möchten?',
      saved: 'Gespeichert',
      save: 'Speichern',
      download: 'Herunterladen',
      clear: 'Löschen',
      placeholder: 'Geben Sie hier Ihre Notizen ein...',
      characterCount: 'Zeichen',
      yourNotes: 'Ihre Notizen',
      lastModified: 'Zuletzt geändert',
      autoSaveTitle: 'Automatisches Speichern',
      autoSaveDescription: 'Ihre Notizen werden automatisch alle paar Sekunden gespeichert.',
      privacyTitle: 'Datenschutz',
      privacyDescription: 'Alle Inhalte werden nur in Ihrem Browser gespeichert.',
      exportTitle: 'Exportieren',
      exportDescription: 'Laden Sie Ihre Notizen als Textdatei herunter.',
    },
    languagesPageTitle: 'Verfügbare Sprachen',
    languagesPageDescription: 'Wählen Sie Ihre bevorzugte Sprache, um auf die Website in Ihrer Muttersprache zuzugreifen.',
    availableLanguages: 'Verfügbare Sprachen',
    currentLanguage: 'Aktuelle Sprache',
    copyUrl: 'URL kopieren',
    urlCopied: 'URL in die Zwischenablage kopiert!',
    selectLanguage: 'Sprache auswählen',
  },
  fr: {
    ...EN_TRANSLATIONS,
    siteTitle: 'Outils en ligne gratuits',
    siteName: 'Outils en ligne',
    siteDescription: 'Accédez à une suite complète d\'outils en ligne gratuits pour l\'édition PDF, la conversion vidéo, le traitement d\'images et la génération de codes QR. Convertissez, compressez et optimisez les fichiers en toute sécurité dans votre navigateur.',
    home: 'Accueil',
    tools: 'Outils',
    about: 'À propos',
    contact: 'Contact',
    privacyPolicy: 'Politique de confidentialité',
    termsOfUse: 'Conditions d\'utilisation',
    sitemap: 'Plan du site',
    languages: 'Langues',
    heroTitle: 'Outils en ligne gratuits',
    heroSubtitle: 'Tout ce dont vous avez besoin en un seul endroit',
    heroDescription: 'Accédez à une collection complète d\'outils en ligne gratuits pour faciliter votre travail et augmenter votre productivité.',
    searchPlaceholder: 'Rechercher des outils...',
    allCategories: 'Tous',
    totalTools: 'Total :',
    toolsCounter: 'outils disponibles',
    notebookTitle: 'Bloc-notes',
    notebookDescription: 'Écrivez et sauvegardez vos notes rapidement.',
    notebook: {
      confirmClear: 'Êtes-vous sûr de vouloir effacer les notes ?',
      saved: 'Sauvegardé',
      save: 'Sauvegarder',
      download: 'Télécharger',
      clear: 'Effacer',
      placeholder: 'Tapez vos notes ici...',
      characterCount: 'caractères',
      yourNotes: 'Vos notes',
      lastModified: 'Dernière modification',
      autoSaveTitle: 'Sauvegarde automatique',
      autoSaveDescription: 'Vos notes sont automatiquement sauvegardées toutes les quelques secondes.',
      privacyTitle: 'Confidentialité',
      privacyDescription: 'Tout le contenu est stocké uniquement dans votre navigateur.',
      exportTitle: 'Exporter',
      exportDescription: 'Téléchargez vos notes sous forme de fichier texte.',
    },
    languagesPageTitle: 'Langues disponibles',
    languagesPageDescription: 'Choisissez votre langue préférée pour accéder au site dans votre langue maternelle.',
    availableLanguages: 'Langues disponibles',
    currentLanguage: 'Langue actuelle',
    copyUrl: 'Copier l\'URL',
    urlCopied: 'URL copiée dans le presse-papiers !',
    selectLanguage: 'Sélectionner la langue',
  },
  it: {
    ...EN_TRANSLATIONS,
    siteTitle: 'Strumenti online gratuiti',
    siteName: 'Strumenti online',
    siteDescription: 'Accedi a una suite completa di strumenti online gratuiti per l\'editing PDF, la conversione video, l\'elaborazione di immagini e la generazione di codici QR. Converti, comprimi e ottimizza i file in modo sicuro nel tuo browser.',
    home: 'Home',
    tools: 'Strumenti',
    about: 'Chi siamo',
    contact: 'Contatto',
    privacyPolicy: 'Politica sulla privacy',
    termsOfUse: 'Termini di utilizzo',
    sitemap: 'Mappa del sito',
    languages: 'Lingue',
    heroTitle: 'Strumenti online gratuiti',
    heroSubtitle: 'Tutto ciò di cui hai bisogno in un unico posto',
    heroDescription: 'Accedi a una collezione completa di strumenti online gratuiti per facilitare il tuo lavoro e aumentare la tua produttività.',
    searchPlaceholder: 'Cerca strumenti...',
    allCategories: 'Tutti',
    totalTools: 'Totale:',
    toolsCounter: 'strumenti disponibili',
    notebookTitle: 'Blocco note',
    notebookDescription: 'Scrivi e salva le tue note rapidamente.',
    notebook: {
      confirmClear: 'Sei sicuro di voler cancellare le note?',
      saved: 'Salvato',
      save: 'Salva',
      download: 'Scarica',
      clear: 'Cancella',
      placeholder: 'Digita le tue note qui...',
      characterCount: 'caratteri',
      yourNotes: 'Le tue note',
      lastModified: 'Ultima modifica',
      autoSaveTitle: 'Salvataggio automatico',
      autoSaveDescription: 'Le tue note vengono salvate automaticamente ogni pochi secondi.',
      privacyTitle: 'Privacy',
      privacyDescription: 'Tutto il contenuto è memorizzato solo nel tuo browser.',
      exportTitle: 'Esporta',
      exportDescription: 'Scarica le tue note come file di testo.',
    },
    languagesPageTitle: 'Lingue disponibili',
    languagesPageDescription: 'Scegli la tua lingua preferita per accedere al sito nella tua lingua madre.',
    availableLanguages: 'Lingue disponibili',
    currentLanguage: 'Lingua attuale',
    copyUrl: 'Copia URL',
    urlCopied: 'URL copiato negli appunti!',
    selectLanguage: 'Seleziona lingua',
  },
  ko: {
    ...EN_TRANSLATIONS,
    siteTitle: '무료 온라인 도구',
    siteName: '온라인 도구',
    siteDescription: 'PDF 편집, 비디오 변환, 이미지 처리 및 QR 코드 생성을 위한 포괄적인 무료 온라인 도구 모음에 액세스하세요. 브라우저에서 안전하게 파일을 변환, 압축 및 최적화하세요.',
    home: '홈',
    tools: '도구',
    about: '소개',
    contact: '연락처',
    privacyPolicy: '개인정보 보호정책',
    termsOfUse: '이용약관',
    sitemap: '사이트맵',
    languages: '언어',
    heroTitle: '무료 온라인 도구',
    heroSubtitle: '필요한 모든 것이 한 곳에',
    heroDescription: '작업을 용이하게 하고 생산성을 높이기 위한 무료 온라인 도구의 완전한 컬렉션에 액세스하세요.',
    searchPlaceholder: '도구 검색...',
    allCategories: '전체',
    totalTools: '총:',
    toolsCounter: '사용 가능한 도구',
    notebookTitle: '메모장',
    notebookDescription: '메모를 빠르게 작성하고 저장하세요.',
    notebook: {
      confirmClear: '정말로 메모를 지우시겠습니까?',
      saved: '저장됨',
      save: '저장',
      download: '다운로드',
      clear: '지우기',
      placeholder: '여기에 메모를 입력하세요...',
      characterCount: '글자',
      yourNotes: '내 메모',
      lastModified: '마지막 수정',
      autoSaveTitle: '자동 저장',
      autoSaveDescription: '메모는 몇 초마다 자동으로 저장됩니다.',
      privacyTitle: '개인정보 보호',
      privacyDescription: '모든 내용은 브라우저에만 저장됩니다.',
      exportTitle: '내보내기',
      exportDescription: '메모를 텍스트 파일로 다운로드하세요.',
    },
    languagesPageTitle: '사용 가능한 언어',
    languagesPageDescription: '모국어로 사이트에 액세스하려면 선호하는 언어를 선택하세요.',
    availableLanguages: '사용 가능한 언어',
    currentLanguage: '현재 언어',
    copyUrl: 'URL 복사',
    urlCopied: 'URL이 클립보드에 복사되었습니다!',
    selectLanguage: '언어 선택',
  },
  tr: {
    ...EN_TRANSLATIONS,
    siteTitle: 'Ücretsiz Çevrimiçi Araçlar',
    siteName: 'Çevrimiçi Araçlar',
    siteDescription: 'PDF düzenleme, video dönüştürme, görüntü işleme ve QR kod oluşturma için kapsamlı ücretsiz çevrimiçi araç paketine erişin. Tarayıcınızda güvenli bir şekilde dosyaları dönüştürün, sıkıştırın ve optimize edin.',
    home: 'Ana Sayfa',
    tools: 'Araçlar',
    about: 'Hakkında',
    contact: 'İletişim',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfUse: 'Kullanım Şartları',
    sitemap: 'Site Haritası',
    languages: 'Diller',
    heroTitle: 'Ücretsiz Çevrimiçi Araçlar',
    heroSubtitle: 'İhtiyacınız olan her şey tek yerde',
    heroDescription: 'İşinizi kolaylaştırmak ve üretkenliğinizi artırmak için ücretsiz çevrimiçi araçların eksiksiz koleksiyonuna erişin.',
    searchPlaceholder: 'Araç ara...',
    allCategories: 'Tümü',
    totalTools: 'Toplam:',
    toolsCounter: 'mevcut araç',
    notebookTitle: 'Not Defteri',
    notebookDescription: 'Notlarınızı hızlıca yazın ve kaydedin.',
    notebook: {
      confirmClear: 'Notları temizlemek istediğinizden emin misiniz?',
      saved: 'Kaydedildi',
      save: 'Kaydet',
      download: 'İndir',
      clear: 'Temizle',
      placeholder: 'Notlarınızı buraya yazın...',
      characterCount: 'karakter',
      yourNotes: 'Notlarınız',
      lastModified: 'Son değişiklik',
      autoSaveTitle: 'Otomatik Kaydetme',
      autoSaveDescription: 'Notlarınız her birkaç saniyede otomatik olarak kaydedilir.',
      privacyTitle: 'Gizlilik',
      privacyDescription: 'Tüm içerik yalnızca tarayıcınızda saklanır.',
      exportTitle: 'Dışa Aktar',
      exportDescription: 'Notlarınızı metin dosyası olarak indirin.',
    },
    languagesPageTitle: 'Mevcut Diller',
    languagesPageDescription: 'Siteye ana dilinizde erişmek için tercih ettiğiniz dili seçin.',
    availableLanguages: 'Mevcut Diller',
    currentLanguage: 'Mevcut Dil',
    copyUrl: 'URL\'yi Kopyala',
    urlCopied: 'URL panoya kopyalandı!',
    selectLanguage: 'Dil Seç',
  },
  pl: {
    ...EN_TRANSLATIONS,
    siteTitle: 'Darmowe narzędzia online',
    siteName: 'Narzędzia online',
    siteDescription: 'Uzyskaj dostęp do kompleksowego zestawu darmowych narzędzi online do edycji PDF, konwersji wideo, przetwarzania obrazów i generowania kodów QR. Konwertuj, kompresuj i optymalizuj pliki bezpiecznie w swojej przeglądarce.',
    home: 'Strona główna',
    tools: 'Narzędzia',
    about: 'O nas',
    contact: 'Kontakt',
    privacyPolicy: 'Polityka prywatności',
    termsOfUse: 'Warunki użytkowania',
    sitemap: 'Mapa strony',
    languages: 'Języki',
    heroTitle: 'Darmowe narzędzia online',
    heroSubtitle: 'Wszystko czego potrzebujesz w jednym miejscu',
    heroDescription: 'Uzyskaj dostęp do kompletnej kolekcji darmowych narzędzi online, aby ułatwić swoją pracę i zwiększyć produktywność.',
    searchPlaceholder: 'Szukaj narzędzi...',
    allCategories: 'Wszystkie',
    totalTools: 'Łącznie:',
    toolsCounter: 'dostępnych narzędzi',
    notebookTitle: 'Notatnik',
    notebookDescription: 'Szybko pisz i zapisuj swoje notatki.',
    notebook: {
      confirmClear: 'Czy na pewno chcesz wyczyścić notatki?',
      saved: 'Zapisano',
      save: 'Zapisz',
      download: 'Pobierz',
      clear: 'Wyczyść',
      placeholder: 'Wpisz swoje notatki tutaj...',
      characterCount: 'znaków',
      yourNotes: 'Twoje notatki',
      lastModified: 'Ostatnia modyfikacja',
      autoSaveTitle: 'Automatyczne zapisywanie',
      autoSaveDescription: 'Twoje notatki są automatycznie zapisywane co kilka sekund.',
      privacyTitle: 'Prywatność',
      privacyDescription: 'Cała zawartość jest przechowywana tylko w Twojej przeglądarce.',
      exportTitle: 'Eksportuj',
      exportDescription: 'Pobierz swoje notatki jako plik tekstowy.',
    },
    languagesPageTitle: 'Dostępne języki',
    languagesPageDescription: 'Wybierz preferowany język, aby uzyskać dostęp do strony w swoim ojczystym języku.',
     availableLanguages: 'Dostępne języki',
     currentLanguage: 'Bieżący język',
     copyUrl: 'Kopiuj URL',
     urlCopied: 'URL skopiowany do schowka!',
     selectLanguage: 'Wybierz język',
   },
   nl: {
     ...EN_TRANSLATIONS,
     siteTitle: 'Gratis online tools',
     siteName: 'Online tools',
     siteDescription: 'Toegang tot een uitgebreide suite van gratis online tools voor PDF-bewerking, videoconversie, beeldverwerking en QR-code generatie. Converteer, comprimeer en optimaliseer bestanden veilig in uw browser.',
     home: 'Home',
     tools: 'Tools',
     about: 'Over ons',
     contact: 'Contact',
     privacyPolicy: 'Privacybeleid',
     termsOfUse: 'Gebruiksvoorwaarden',
     sitemap: 'Sitemap',
     languages: 'Talen',
     heroTitle: 'Gratis online tools',
     heroSubtitle: 'Alles wat je nodig hebt op één plek',
     heroDescription: 'Toegang tot een complete collectie gratis online tools om uw werk te vergemakkelijken en uw productiviteit te verhogen.',
     searchPlaceholder: 'Zoek tools...',
     allCategories: 'Alle',
     totalTools: 'Totaal:',
     toolsCounter: 'beschikbare tools',
     notebookTitle: 'Notitieblok',
     notebookDescription: 'Schrijf en bewaar uw notities snel.',
     notebook: {
       confirmClear: 'Weet u zeker dat u de notities wilt wissen?',
       saved: 'Opgeslagen',
       save: 'Opslaan',
       download: 'Downloaden',
       clear: 'Wissen',
       placeholder: 'Typ hier uw notities...',
       characterCount: 'tekens',
       yourNotes: 'Uw notities',
       lastModified: 'Laatst gewijzigd',
       autoSaveTitle: 'Automatisch opslaan',
       autoSaveDescription: 'Uw notities worden automatisch elke paar seconden opgeslagen.',
       privacyTitle: 'Privacy',
       privacyDescription: 'Alle inhoud wordt alleen in uw browser opgeslagen.',
       exportTitle: 'Exporteren',
       exportDescription: 'Download uw notities als tekstbestand.',
     },
     languagesPageTitle: 'Beschikbare talen',
     languagesPageDescription: 'Kies uw voorkeurstaal om de site in uw moedertaal te bezoeken.',
     availableLanguages: 'Beschikbare talen',
     currentLanguage: 'Huidige taal',
     copyUrl: 'URL kopiëren',
     urlCopied: 'URL gekopieerd naar klembord!',
     selectLanguage: 'Selecteer taal',
   },
   sv: {
     ...EN_TRANSLATIONS,
     siteTitle: 'Gratis onlineverktyg',
     siteName: 'Onlineverktyg',
     siteDescription: 'Få tillgång till en omfattande svit av gratis onlineverktyg för PDF-redigering, videokonvertering, bildbehandling och QR-kodgenerering. Konvertera, komprimera och optimera filer säkert i din webbläsare.',
     home: 'Hem',
     tools: 'Verktyg',
     about: 'Om oss',
     contact: 'Kontakt',
     privacyPolicy: 'Integritetspolicy',
     termsOfUse: 'Användarvillkor',
     sitemap: 'Webbplatskarta',
     languages: 'Språk',
     heroTitle: 'Gratis onlineverktyg',
     heroSubtitle: 'Allt du behöver på ett ställe',
     heroDescription: 'Få tillgång till en komplett samling gratis onlineverktyg för att underlätta ditt arbete och öka din produktivitet.',
     searchPlaceholder: 'Sök verktyg...',
     allCategories: 'Alla',
     totalTools: 'Totalt:',
     toolsCounter: 'tillgängliga verktyg',
     notebookTitle: 'Anteckningsblock',
     notebookDescription: 'Skriv och spara dina anteckningar snabbt.',
     notebook: {
       confirmClear: 'Är du säker på att du vill rensa anteckningarna?',
       saved: 'Sparad',
       save: 'Spara',
       download: 'Ladda ner',
       clear: 'Rensa',
       placeholder: 'Skriv dina anteckningar här...',
       characterCount: 'tecken',
       yourNotes: 'Dina anteckningar',
       lastModified: 'Senast ändrad',
       autoSaveTitle: 'Automatisk sparning',
       autoSaveDescription: 'Dina anteckningar sparas automatiskt var några sekunder.',
       privacyTitle: 'Integritet',
       privacyDescription: 'Allt innehåll lagras endast i din webbläsare.',
       exportTitle: 'Exportera',
       exportDescription: 'Ladda ner dina anteckningar som textfil.',
     },
     languagesPageTitle: 'Tillgängliga språk',
     languagesPageDescription: 'Välj ditt föredragna språk för att komma åt webbplatsen på ditt modersmål.',
     availableLanguages: 'Tillgängliga språk',
     currentLanguage: 'Nuvarande språk',
     copyUrl: 'Kopiera URL',
     urlCopied: 'URL kopierad till urklipp!',
     selectLanguage: 'Välj språk',
   },
   uk: {
     ...EN_TRANSLATIONS,
     siteTitle: 'Безкоштовні онлайн інструменти',
     siteName: 'Онлайн інструменти',
     siteDescription: 'Отримайте доступ до комплексного набору безкоштовних онлайн інструментів для редагування PDF, конвертації відео, обробки зображень та генерації QR-кодів. Конвертуйте, стискайте та оптимізуйте файли безпечно у вашому браузері.',
     home: 'Головна',
     tools: 'Інструменти',
     about: 'Про нас',
     contact: 'Контакти',
     privacyPolicy: 'Політика конфіденційності',
     termsOfUse: 'Умови використання',
     sitemap: 'Карта сайту',
     languages: 'Мови',
     heroTitle: 'Безкоштовні онлайн інструменти',
     heroSubtitle: 'Все що потрібно в одному місці',
     heroDescription: 'Отримайте доступ до повної колекції безкоштовних онлайн інструментів для полегшення роботи та підвищення продуктивності.',
     searchPlaceholder: 'Пошук інструментів...',
     allCategories: 'Всі',
     totalTools: 'Всього:',
     toolsCounter: 'доступних інструментів',
     notebookTitle: 'Блокнот',
     notebookDescription: 'Швидко записуйте та зберігайте свої нотатки.',
     notebook: {
       confirmClear: 'Ви впевнені, що хочете очистити нотатки?',
       saved: 'Збережено',
       save: 'Зберегти',
       download: 'Завантажити',
       clear: 'Очистити',
       placeholder: 'Введіть ваші нотатки тут...',
       characterCount: 'символів',
       yourNotes: 'Ваші нотатки',
       lastModified: 'Остання зміна',
       autoSaveTitle: 'Автозбереження',
       autoSaveDescription: 'Ваші нотатки автоматично зберігаються кожні кілька секунд.',
       privacyTitle: 'Конфіденційність',
       privacyDescription: 'Весь контент зберігається тільки у вашому браузері.',
       exportTitle: 'Експорт',
       exportDescription: 'Завантажте ваші нотатки як текстовий файл.',
     },
     languagesPageTitle: 'Доступні мови',
     languagesPageDescription: 'Оберіть вашу бажану мову для доступу до сайту рідною мовою.',
     availableLanguages: 'Доступні мови',
     currentLanguage: 'Поточна мова',
     copyUrl: 'Копіювати URL',
     urlCopied: 'URL скопійовано в буфер обміну!',
     selectLanguage: 'Обрати мову',
   },
   vi: {
     ...EN_TRANSLATIONS,
     siteTitle: 'Công cụ trực tuyến miễn phí',
     siteName: 'Công cụ trực tuyến',
     siteDescription: 'Truy cập bộ công cụ trực tuyến miễn phí toàn diện để chỉnh sửa PDF, chuyển đổi video, xử lý hình ảnh và tạo mã QR. Chuyển đổi, nén và tối ưu hóa tệp một cách an toàn trong trình duyệt của bạn.',
     home: 'Trang chủ',
     tools: 'Công cụ',
     about: 'Giới thiệu',
     contact: 'Liên hệ',
     privacyPolicy: 'Chính sách bảo mật',
     termsOfUse: 'Điều khoản sử dụng',
     sitemap: 'Sơ đồ trang web',
     languages: 'Ngôn ngữ',
     heroTitle: 'Công cụ trực tuyến miễn phí',
     heroSubtitle: 'Mọi thứ bạn cần ở một nơi',
     heroDescription: 'Truy cập bộ sưu tập đầy đủ các công cụ trực tuyến miễn phí để hỗ trợ công việc và tăng năng suất của bạn.',
     searchPlaceholder: 'Tìm kiếm công cụ...',
     allCategories: 'Tất cả',
     totalTools: 'Tổng cộng:',
     toolsCounter: 'công cụ có sẵn',
     notebookTitle: 'Sổ ghi chú',
     notebookDescription: 'Viết và lưu ghi chú của bạn một cách nhanh chóng.',
     notebook: {
       confirmClear: 'Bạn có chắc chắn muốn xóa ghi chú không?',
       saved: 'Đã lưu',
       save: 'Lưu',
       download: 'Tải xuống',
       clear: 'Xóa',
       placeholder: 'Nhập ghi chú của bạn tại đây...',
       characterCount: 'ký tự',
       yourNotes: 'Ghi chú của bạn',
       lastModified: 'Lần sửa đổi cuối',
       autoSaveTitle: 'Tự động lưu',
       autoSaveDescription: 'Ghi chú của bạn được tự động lưu mỗi vài giây.',
       privacyTitle: 'Quyền riêng tư',
       privacyDescription: 'Tất cả nội dung chỉ được lưu trữ trong trình duyệt của bạn.',
       exportTitle: 'Xuất',
       exportDescription: 'Tải xuống ghi chú của bạn dưới dạng tệp văn bản.',
     },
     languagesPageTitle: 'Ngôn ngữ có sẵn',
     languagesPageDescription: 'Chọn ngôn ngữ ưa thích của bạn để truy cập trang web bằng ngôn ngữ mẹ đẻ.',
     availableLanguages: 'Ngôn ngữ có sẵn',
     currentLanguage: 'Ngôn ngữ hiện tại',
     copyUrl: 'Sao chép URL',
     urlCopied: 'URL đã được sao chép vào clipboard!',
     selectLanguage: 'Chọn ngôn ngữ',
   },
   th: {
     ...EN_TRANSLATIONS,
     siteTitle: 'เครื่องมือออนไลน์ฟรี',
     siteName: 'เครื่องมือออนไลน์',
     siteDescription: 'เข้าถึงชุดเครื่องมือออนไลน์ฟรีที่ครอบคลุมสำหรับการแก้ไข PDF การแปลงวิดีโอ การประมวลผลภาพ และการสร้างรหัส QR แปลง บีบอัด และปรับแต่งไฟล์อย่างปลอดภัยในเบราว์เซอร์ของคุณ',
     home: 'หน้าแรก',
     tools: 'เครื่องมือ',
     about: 'เกี่ยวกับ',
     contact: 'ติดต่อ',
     privacyPolicy: 'นโยบายความเป็นส่วนตัว',
     termsOfUse: 'เงื่อนไขการใช้งาน',
     sitemap: 'แผนผังเว็บไซต์',
     languages: 'ภาษา',
     heroTitle: 'เครื่องมือออนไลน์ฟรี',
     heroSubtitle: 'ทุกสิ่งที่คุณต้องการในที่เดียว',
     heroDescription: 'เข้าถึงคอลเลกชันที่สมบูรณ์ของเครื่องมือออนไลน์ฟรีเพื่อช่วยให้งานของคุณง่ายขึ้นและเพิ่มประสิทธิภาพ',
     searchPlaceholder: 'ค้นหาเครื่องมือ...',
     allCategories: 'ทั้งหมด',
     totalTools: 'รวม:',
     toolsCounter: 'เครื่องมือที่มีอยู่',
     notebookTitle: 'สมุดบันทึก',
     notebookDescription: 'เขียนและบันทึกโน้ตของคุณอย่างรวดเร็ว',
     notebook: {
       confirmClear: 'คุณแน่ใจหรือไม่ว่าต้องการล้างโน้ต?',
       saved: 'บันทึกแล้ว',
       save: 'บันทึก',
       download: 'ดาวน์โหลด',
       clear: 'ล้าง',
       placeholder: 'พิมพ์โน้ตของคุณที่นี่...',
       characterCount: 'ตัวอักษร',
       yourNotes: 'โน้ตของคุณ',
       lastModified: 'แก้ไขล่าสุด',
       autoSaveTitle: 'บันทึกอัตโนมัติ',
       autoSaveDescription: 'โน้ตของคุณจะถูกบันทึกอัตโนมัติทุกๆ ไม่กี่วินาที',
       privacyTitle: 'ความเป็นส่วนตัว',
       privacyDescription: 'เนื้อหาทั้งหมดจะถูกเก็บไว้ในเบราว์เซอร์ของคุณเท่านั้น',
       exportTitle: 'ส่งออก',
       exportDescription: 'ดาวน์โหลดโน้ตของคุณเป็นไฟล์ข้อความ',
     },
     languagesPageTitle: 'ภาษาที่มีอยู่',
     languagesPageDescription: 'เลือกภาษาที่คุณต้องการเพื่อเข้าถึงเว็บไซต์ในภาษาแม่ของคุณ',
     availableLanguages: 'ภาษาที่มีอยู่',
     currentLanguage: 'ภาษาปัจจุบัน',
     copyUrl: 'คัดลอก URL',
     urlCopied: 'คัดลอก URL ไปยังคลิปบอร์ดแล้ว!',
     selectLanguage: 'เลือกภาษา',
   },
 };
 
 export { TRANSLATIONS };
 export default TRANSLATIONS;
